# Rebuilds kb/vulnerable-drivers.txt from the LOLDrivers project
# (https://www.loldrivers.io, Apache License 2.0).
#   python scripts/update-driver-list.py
# Each line: first 16 hex digits of the SHA-256, category (v = vulnerable,
# m = malicious), file name. 64 bits of the hash keep the file small while a
# false match stays practically impossible.
import json
import pathlib
import urllib.request

URL = "https://www.loldrivers.io/api/drivers.json"
OUT = pathlib.Path(__file__).resolve().parent.parent / "kb" / "vulnerable-drivers.txt"

with urllib.request.urlopen(URL, timeout=120) as r:
    drivers = json.load(r)

rows = {}
for d in drivers:
    cat = "m" if (d.get("Category") or "").lower().startswith("malicious") else "v"
    for s in d.get("KnownVulnerableSamples") or []:
        h = (s.get("SHA256") or "").strip().lower()
        if len(h) != 64:
            continue
        name = (s.get("Filename") or s.get("OriginalFilename") or "").strip().replace(" ", "_") or "?"
        rows.setdefault(h[:16], (cat, name[:40]))

lines = [
    "# Known vulnerable and malicious Windows drivers, from LOLDrivers",
    "# (https://www.loldrivers.io, Apache License 2.0). Generated by",
    "# scripts/update-driver-list.py: SHA-256 prefix, v/m, file name.",
]
lines += [f"{h} {c} {n}" for h, (c, n) in sorted(rows.items())]
OUT.write_text("\n".join(lines) + "\n", encoding="ascii", errors="replace")
print(f"{len(rows)} drivers -> {OUT}")
