[package]
name = "syscura-online"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
syscura-core = { path = "../syscura-core" }
ureq = "3.4.2"

[target."cfg(windows)".dependencies]
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_Security_Credentials"] }
